# Generated by Django 5.0.1 on 2024-02-17 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_avatar_friend_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='profile',
        ),
        migrations.AddField(
            model_name='friend',
            name='profile_one',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='friendships_one', to='user.profile'),
        ),
        migrations.AddField(
            model_name='friend',
            name='profile_two',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='friendships_two', to='user.profile'),
        ),
    ]
