# Generated by Django 5.0.1 on 2024-02-17 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_friend_profile_friend_profile_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='profile_one',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='friendships_one', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='profile_two',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='friendships_two', to='user.profile'),
        ),
    ]
